[package]
name = "somc-report"
version = "0.1.0"
edition = "2021"

[dependencies]
"somc-global" = { path = "../somc-global" }
"somc-lex" = { path = "../somc-lex" }

yansi = "0.5.1"
json = "0.12.4"
num_enum = "0.5.7"
convert_case = "0.5.0"