[book]
title = "Som Documentation"
authors = ["Sjoerd Vermeulen"]
description = "The documentation for the Som programming language."
language = "en"

[output.html]
default-theme = "latte"
preferred-dark-theme = "mocha"
git-repository-url = "https://github.com/SjVer/Som-Lang"
additional-css = ["theme/theme.css", "theme/highlight.css", "theme/tweaks.css"]
additional-js = ["js/som-ace.js", "js/som-hljs.js", "js/som-editor.js"]

[output.html.playground]
editable = true
copyable = true
# line-numbers = true
runnable = true

[build]
extra-watch-dirs = ["js", "theme"]

[preprocessor.chapter-number]
renderer = ["html"]

[preprocessor.gen-sources]
renderer = ["html"]
before = ["links"]
output-dir = "sources"
command = "python3 gen_sources.py"
